spring:
   #mysql
   datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: lzq52410
    #jpa
   jpa:
     hibernate:
       ddl-auto: none
     show-sql: true
#log
server:
  port: 8081

logging:
  level: warn

