spring:
#mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.97.104.77:3306/blog
    username: root
    password: lzq52410
    #jpa
  jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
#server
server:
  port: 8082
#log
logging:
  file:
    name: log/dev/dev.log

